"""add rows_deleted to ingestion_jobs

Revision ID: 1677b437ffb6
Revises: f5205fcc61fc
Create Date: 2026-08-20 14:55:59.159513
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1677b437ffb6"
down_revision: str | None = "f5205fcc61fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so this is safe against a table that already has rows, not just
    # the currently-empty one - matches the ORM-level default=0 for new rows.
    op.add_column(
        "ingestion_jobs",
        sa.Column("rows_deleted", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingestion_jobs", "rows_deleted")
    # ### end Alembic commands ###
