"""add llm usage

Revision ID: 7260b347df31
Revises: 1677b437ffb6
Create Date: 2026-08-22 18:18:11.760096
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7260b347df31"
down_revision: str | None = "1677b437ffb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Pure additive create_table, no data migration - Day 6's per-merchant cost
    # ledger (`app.models.db.LlmUsage`). Autogenerate also proposed dropping
    # `ingestion_jobs.rows_deleted`'s `server_default` here - that's pre-existing
    # drift between the ORM's Python-side `default=0` and the live column's
    # `server_default='0'` (set deliberately in `1677b437ffb6`, unrelated to this
    # change) - left alone rather than folded into an unrelated migration.
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_creation_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=14, scale=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_llm_usage_merchant_created", "llm_usage", ["merchant_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_llm_usage_merchant_id"), "llm_usage", ["merchant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_usage_merchant_id"), table_name="llm_usage")
    op.drop_index("ix_llm_usage_merchant_created", table_name="llm_usage")
    op.drop_table("llm_usage")
    # ### end Alembic commands ###
